name: "Build and deploy"

on:
        push:
                branches:
                        - master

jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                - name: Fetch master branch
                  uses: actions/checkout@v2
          
                - name: Grant gradle rights
                  run: chmod +x ./gradlew

                - name: Build Release APK with Gradle
                  run: ./gradlew clean assembleRelease
                
                - name: Build release
                  uses: r0adkll/sign-android-release@v1
                  with:
                        releaseDirectory: app/build/outputs/apk/release
                        signingKeyBase64: ${{ secrets.THREE_SIGNING_KEY }}
                        alias: ${{ secrets.THREE_ALIAS }}
                        keyStorePassword: ${{ secrets.THREE_KEY_STORE_PASSWORD }}
                        keyPassword: ${{ secrets.THREE_KEY_PASSWORD }}

                - name: Upload Android Release to Play Store
                  uses: r0adkll/upload-google-play@v1
                  with:
                        serviceAccountJsonPlainText: ${{ secrets.THREE_SERVICE_ACCOUNT_JSON }}
                        packageName: com.josealfonsomora.threebalance
                        releaseFile: app/build/outputs/apk/release/app-release-unsigned-signed.apk
                        track: beta
